// deliver-front/react/src/views/SystemManage/pages/MyAccount/index.tsx
import React, { useRef, useState } from 'react';
import { Card, Button, Drawer, Form, Input, message } from 'antd';
import { updatePwd } from '@/api/user';
import { omitProperty } from '@/utils/omitProperty';
import { useVerify } from '@/hooks/useVerify';
import styles from './index.module.scss';
import { passwordValidationRule, verificationCodeValidationRule } from '@/views/Login/constant';

const MyAccount: React.FC = () => {
  const myAccountRef = useRef<any>(null);
  const [open, setOpen] = useState(false);
  const userInfo = JSON.parse(localStorage.getItem('userInfo') as string);
  const userEmail = userInfo?.userEmail || '1957214211@qq.com';

  const [editorData, setEditorData] = useState({
    userPassword: '',
    confirmPwd: '',
    verificationCode: '',
    userEmail
  });

  const { verifyContent, verifyDisabled, handleVerify } = useVerify({
    email: localStorage.getItem('user_email') || '1957214211@qq.com'
  });

  const validatePwd = (_: any, value: string) => {
    if (value !== editorData.userPassword || !value) {
      return Promise.reject('两次输入密码不相同');
    }
    return Promise.resolve();
  };

  const onSubmit = async () => {
    try {
      await myAccountRef.current.validateFields();
      await updatePwd(omitProperty(editorData, 'confirmPwd'));
      message.success('修改密码成功');
      setOpen(false);
    } catch (error) {
      console.log('error', error);
    }
  };

  return (
    <Card title="基础信息" className={styles['ant_card']}>
      <div className={styles['card_content']}>
        <p>邮箱: {userInfo?.userEmail}</p>
        <p>姓名: {userInfo?.userRealName}</p>
        <p>用户类型: {userInfo?.userRole}</p>
        <Button onClick={() => setOpen(true)}>修改密码</Button>
      </div>
      <Drawer
        title="修改密码"
        open={open}
        placement="right"
        onClose={() => setOpen(false)}
        extra={
          <>
            <Button style={{ marginRight: 8 }} onClick={() => setOpen(false)}>
              取消
            </Button>
            <Button type="primary" onClick={onSubmit}>
              确认
            </Button>
          </>
        }
      >
        <Form
          ref={myAccountRef}
          initialValues={editorData}
          onValuesChange={(changedValues) => {
            setEditorData((prev) => ({ ...prev, ...changedValues }));
            if (editorData.confirmPwd && changedValues.userPassword) {
              myAccountRef.current.validateFields(['confirmPwd']);
            }
          }}
        >
          <Form.Item
            name="userPassword"
            rules={[passwordValidationRule]}
            validateTrigger={['onBlur']}
          >
            <Input.Password placeholder="请输入密码" maxLength={16} />
          </Form.Item>
          <Form.Item
            name="confirmPwd"
            rules={[{ validator: validatePwd }]}
            validateTrigger={['onBlur']}
          >
            <Input.Password placeholder="请确认密码" maxLength={16} />
          </Form.Item>
          <Form.Item
            name="verificationCode"
            rules={[verificationCodeValidationRule]}
            validateTrigger={['onBlur']}
          >
            <div className={styles['verify']}>
              <Input placeholder="请输入6位验证码" maxLength={6} />
              <Button
                className={styles['verify_btn']}
                disabled={verifyDisabled}
                onClick={() => handleVerify()}
              >
                {verifyContent}
              </Button>
            </div>
          </Form.Item>
        </Form>
      </Drawer>
    </Card>
  );
};

export default MyAccount;

// deliver-front/vue/src/views/SystemManage/pages/MyAccount/index.vue
<script lang="ts" setup>
import { ref, reactive } from 'vue';
import type { Rule } from 'ant-design-vue/es/form';
import { updatePwd } from '@/api/user';
import { omitProperty } from '@/utils/utils';
import { message } from 'ant-design-vue';
import { getRules } from '@/config/rules';
import { useVerify } from '@/utils/hooks';
import { UserInfo } from '@/views/Login/type';

const userInfo: UserInfo = JSON.parse(localStorage.getItem("user_info") as string)
const editorData = reactive({
	userPassword: '',
	confirmPwd: '',
	verificationCode: ''
})
const open = ref<boolean>(false);
const formRef = ref()
const showDrawer = () => {
	open.value = true;
};
const onClose = () => {
	open.value = false;
};
const onSubmit = () => {
	formRef.value
		.validate()
		.then(async () => {
			await updatePwd(omitProperty(editorData, "confirmPwd"))
			message.success("修改密码成功")
			onClose()
		})
		.catch(error => {
			console.log('error', error);
		});
};

const validatePwd = () => {
	return editorData.confirmPwd === editorData.userPassword ? Promise.resolve() : Promise.reject("两次输入密码不相同")
}
const rules: Record<string, Rule[]> = {
	confirmPwd: [{ required: true, message: '请确认密码!', trigger: 'blur' }, { validator: validatePwd, trigger: 'blur' }],
	...getRules(['userPassword', 'verificationCode'])
};
const { state, handleVarify } = useVerify()
state.verifyDisabled = false
</script>

<template>
	<a-card title="基础信息">
		<div class="card_content">
			<p>邮箱: {{ userInfo.userEmail }}</p>
			<p>姓名: {{ userInfo.userRealName }}</p>
			<p>用户类型: {{ userInfo.userRole }}</p>
			<a-button @click="showDrawer">修改密码</a-button>
		</div>
		<a-drawer title="修改密码" :open="open" placement="right" @close="onClose">
			<a-form ref="formRef" :model="editorData" :rules="rules">
				<a-form-item name="userPassword">
					<a-input-password v-model:value.trim="editorData.userPassword" placeholder="请输入密码" />
				</a-form-item>
				<a-form-item name="confirmPwd">
					<a-input-password v-model:value.trim="editorData.confirmPwd" placeholder="请确认密码" />
				</a-form-item>
				<a-form-item name="verificationCode">
					<div class="verify">
						<a-input v-model:value.trim="editorData.verificationCode" placeholder="请输入验证码" />
						<a-button class="verify_btn" :disabled="state.verifyDisabled" @click="handleVarify(userInfo.userEmail)">{{
							state.verifyContent
						}}</a-button>
					</div>
				</a-form-item>
			</a-form>
			<template #extra>
				<a-button style="margin-right: 8px" @click="onClose">取消</a-button>
				<a-button type="primary" @click="onSubmit">确认</a-button>
			</template>
		</a-drawer>
	</a-card>
</template>

<style lang="scss" scoped>
.ant-card {
	width: 500px;

	.card_content {
		text-align: center;
	}

	p {
		margin: var(--spacing-md) 0;
	}
}

.verify {
	display: flex;

	.verify_btn {
		margin-left: var(--spacing-sm)
	}
}
</style>
