// deliver-front/react/src/views/GroupManage/index.tsx
import React, { useState, useEffect } from 'react';
import { Drawer, Form, Input, Button, message } from 'antd';
import { Outlet, useLocation } from 'react-router-dom';
import Card from './components/Card';
import { addGroup, getGroupData, updateGroup, deleteGroup, toTopGroup } from '@/api/group';
import { GroupCard, GroupCardList } from './type';
import styles from './index.module.scss';
import { groupDescriptionRule, groupNameRule } from './constant';
import { SearchOutlined } from '@ant-design/icons';

const GroupManage: React.FC = () => {
  const location = useLocation();
  const [form] = Form.useForm();

  const [state, setState] = useState({
    mainPage: true,
    open: false,
    operation: 'add' as 'add' | 'edit' | 'delete' | 'toTop',
    search: ''
  });

  const [groupList, setGroupList] = useState<GroupCardList>({
    topUpGroupList: [],
    defaultGroupList: []
  });

  const [groupFormData, setGroupFormData] = useState<GroupCard>({
    groupId: 0,
    groupName: '',
    groupDescription: ''
  });

  const fetchCardData = async (groupName: string = '') => {
    const res = await getGroupData({ groupName });
    setGroupList(res);
  };

  const handleSuccess = async (operation: 'add' | 'edit' | 'delete' | 'toTop') => {
    try {
      await form.validateFields();
      const operations = {
        add: async () => {
          const res = await addGroup(groupFormData);
          if (res) message.success('新增成功');
        },
        edit: async () => {
          const res = await updateGroup(groupFormData);
          if (res) message.success('编辑成功');
        },
        delete: async () => {
          const res = await deleteGroup(groupFormData.groupId);
          if (res) message.success('删除成功');
        },
        toTop: async () => {
          const res = await toTopGroup({ ids: [groupFormData.groupId] });
          if (res) message.success('置顶成功');
        }
      };
      await operations[operation]();
      onClose();
      fetchCardData();
    } catch (error) {
      console.error(error);
    }
  };

  const onOpen = () => setState((prev) => ({ ...prev, open: true }));
  const onClose = () => {
    setState((prev) => ({ ...prev, open: false }));
    // 重置表单数据为初始状态
    setGroupFormData({
      groupId: 0,
      groupName: '',
      groupDescription: ''
    });
    // 重置表单验证状态
    form.resetFields();
  };

  useEffect(() => {
    const checkMainPage = async () => {
      if (!localStorage.getItem('group_id') && location.pathname === '/groupManage') {
        setState((prev) => ({ ...prev, mainPage: true }));
        await fetchCardData();
      } else {
        setState((prev) => ({ ...prev, mainPage: false }));
      }
    };

    checkMainPage();
  }, [location.pathname]);

  useEffect(() => {
    fetchCardData();
  }, []);

  const changeOperation = async (op: 'add' | 'edit' | 'delete' | 'toTop', data?: GroupCard) => {
    setState((prev) => ({ ...prev, operation: op }));
    console.log(data);

    // 对于编辑操作，更新表单数据
    if (op === 'edit' && data) {
      setGroupFormData(data);
      // 重置表单并设置初始值
      form.resetFields();
      form.setFieldsValue(data);
    }

    // 对于新增操作，重置表单
    if (op === 'add') {
      setGroupFormData({
        groupId: 0,
        groupName: '',
        groupDescription: ''
      });
      form.resetFields();
    }

    if (op === 'add' || op === 'edit') onOpen();
    else handleSuccess(op);
  };

  return state.mainPage ? (
    <div>
      <div className={styles['card-top']}>
        <h3>置顶分组</h3>
        <div className={styles['top-cards']}>
          {groupList.topUpGroupList.map((item) => (
            <Card key={item.groupId} data={item} />
          ))}
        </div>
      </div>
      <div className={styles['card-bottom']}>
        <div className={styles['bottom-section']}>
          <h3>全部分组</h3>
          <div className={styles['search-box']}>
            <Button
              className={styles['search-btn']}
              shape="circle"
              icon={<SearchOutlined />}
              onClick={() => fetchCardData}
            />
            <Input
              value={state.search}
              type="text"
              className="search-txt"
              placeholder="请输入分组名"
            />
          </div>
        </div>
        <div className={styles['bottom-cards']}>
          <Card isEmpty onClick={() => changeOperation('add')} />
          {groupList.defaultGroupList.map((item) => (
            <Card
              key={item.groupId}
              data={item}
              showAction
              onTop={() => changeOperation('toTop', item)}
              onEdit={() => changeOperation('edit', item)}
              onDelete={() => changeOperation('delete', item)}
            />
          ))}
        </div>
      </div>
      <Drawer
        width={500}
        title={state.operation === 'add' ? '新增分组' : '编辑分组'}
        placement="right"
        open={state.open}
        onClose={onClose}
        extra={
          <>
            <Button style={{ marginRight: 8 }} onClick={onClose}>
              取消
            </Button>
            <Button type="primary" onClick={() => handleSuccess(state.operation)}>
              确定
            </Button>
          </>
        }
      >
        <Form
          form={form}
          initialValues={groupFormData}
          onValuesChange={(changedValues) =>
            setGroupFormData((prev) => ({ ...prev, ...changedValues }))
          }
          name="basic"
          labelCol={{ span: 5 }}
        >
          <Form.Item label="分组名" name="groupName" required rules={[groupNameRule]}>
            <Input placeholder="请输入分组名" maxLength={10} />
          </Form.Item>
          <Form.Item
            label="分组描述"
            name="groupDescription"
            required
            rules={[groupDescriptionRule]}
          >
            <Input.TextArea placeholder="请输入分组描述" maxLength={50} />
          </Form.Item>
        </Form>
      </Drawer>
    </div>
  ) : (
    <Outlet />
  );
};

export default GroupManage;

// deliver-front/vue/src/views/GroupManage/index.vue
<script lang="ts" setup>
import { ref, reactive, watch, h } from 'vue';
import { useRouter } from 'vue-router';
import Card from './components/Card.vue';
import { addGroup, getGroupData, updateGroup, deleteGroup, toTopGroup } from '@/api/group';
import { GroupCard, GroupCardList } from '@/types/group';
import { getRules } from '@/config/rules';
import { message } from 'ant-design-vue';
import { SearchOutlined } from '@ant-design/icons-vue';
const router = useRouter()
const state = reactive({
	mainPage: true,
	open: false,
	operation: 'add',
	search: '',
})
const onOpen = () => {
	state.open = true
}
const onClose = () => {
	state.open = false
}
const groupList = reactive<GroupCardList>({
	topUpGroupList: [],
	defaultGroupList: []
})
const groupFormData = reactive<GroupCard>({
	groupId: -1,
	groupName: '',
	groupDescription: '',
})
const flashData = async (groupName: string = '') => {
	const res = await getGroupData({ groupName: groupName })
	Object.assign(groupList, res)
}
const onOk = (cb: () => void) => {
	formRef.value
		.validate()
		.then(async () => {
			cb()
			onClose()
			flashData()
		})
		.catch(error => {
			console.log('error', error);
		});
}
const formMeta = {
	add: {
		title: '添加分组',
		success: () => {
			onOk(async () => {
				await addGroup(groupFormData)
				message.success('添加成功')
			})
		}
	},
	edit: {
		title: '编辑分组',
		success: () => {
			onOk(async () => {
				await updateGroup(groupFormData)
				message.success('编辑成功')
			})
		}
	},
	delete: {
		title: '删除分组',
		success: async () => {
			await deleteGroup({ ids: [groupFormData.groupId] })
			message.success('删除成功')
			flashData()
		}
	},
	toTop: {
		success: async () => {
			await toTopGroup({ groupId: groupFormData.groupId })
			flashData()
		}
	}
}
const groupRules = getRules(['groupName', 'groupDescription'])
const formRef = ref()
watch(() => router.currentRoute.value.path, async (to: string) => {
	if (!!!localStorage.getItem('group_id') && to === '/groupManage') {
		state.mainPage = true
		return flashData()
	}
	state.mainPage = false
}, { immediate: true })

const changeOperation = (op: 'add' | 'edit' | 'delete' | 'top', data?: GroupCard) => {
	state.operation = op
	data && Object.assign(groupFormData, data);
	(op === 'add' || op === 'edit') && onOpen()
	op === 'delete' && formMeta.delete.success()
	op === 'top' && formMeta.toTop.success()
}

</script>

<template>
	<div class="groupManage">
		<template v-if="state.mainPage">
			<div class="card-top">
				<h3>置顶分组</h3>
				<div class="top_cards">
					<Card v-for="item in groupList.topUpGroupList" :data="item" @on-top="changeOperation('top', item)"
						@on-edit="changeOperation('edit', item)" @on-delete="changeOperation('delete', item)"></Card>
				</div>
			</div>
			<div class="card-bottom">
				<div class="bottom-section">
					<h3>全部分组</h3>
					<div class="search-box">
						<a-button class="search-btn" shape="circle" :icon="h(SearchOutlined)" @click="flashData(state.search)" />
						<input v-model="state.search" type="text" class="search-txt" placeholder="请输入分组名" />
					</div>
				</div>
				<div class="bottom_cards">
					<Card is-empty @click="changeOperation('add')"></Card>
					<Card showAction v-for="item in groupList.defaultGroupList" :data="item"
						@on-top="changeOperation('top', item)" @on-edit="changeOperation('edit', item)"
						@on-delete="changeOperation('delete', item)"></Card>
				</div>
			</div>
			<a-drawer :width="500" :title="formMeta[state.operation].title" placement="right" :open="state.open"
				@close="onClose">
				<template #extra>
					<a-button style="margin-right: 8px" @click="onClose">取消</a-button>
					<a-button type="primary" @click="formMeta[state.operation].success">确定</a-button>
				</template>
				<a-form ref="formRef" :model="groupFormData" name="basic" :rules="groupRules" :label-col="{ span: 4 }">
					<a-form-item label="分组名" name="groupName">
						<a-input v-model:value="groupFormData.groupName" />
					</a-form-item>
					<a-form-item label="分组描述" name="groupDescription">
						<a-textarea v-model:value="groupFormData.groupDescription" />
					</a-form-item>
				</a-form>
			</a-drawer>
		</template>
		<template v-else>
			<RouterView />
		</template>
	</div>
</template>

<style lang="scss" scoped>
.top_cards,
.bottom_cards {
	display: flex;
	gap: var(--spacing-md);
}

.card-top {
	margin-bottom: var(--spacing-md);

	h3 {
		margin-bottom: var(--spacing-md);
	}
}


.bottom-section {
	display: flex;
	justify-content: space-between;
	align-items: center;
	margin-bottom: var(--spacing-md);

	h3 {
		margin-right: var(--spacing-md);
	}
}


.search-box {
	background-color: white;
	box-shadow: 0 2px 25px 0 rgba(0, 0, 0, 0.1);
	height: 40px;
	border-radius: 40px;
	display: flex;
	margin-right: var(--spacing-md);
}

.search-txt {
	border: none;
	background: none;
	outline: none;
	padding: 0;
	color: #222;
	font-size: 16px;
	// line-height: 40px;
	width: 0;
	transition: 0.4s;
}

.search-btn {
	border: none;
	width: 40px;
	height: 40px;
	border-radius: 50%;
	display: flex;
	justify-content: center;
	align-items: center;
	cursor: pointer;
	transition: 0.4s;
}

.search-box:hover .search-txt {
	width: 200px;
	padding: 0 12px;
}

.search-box:hover .search-btn {
	background-color: #fff;
	animation: rotate 0.4s linear;
}

.search-txt:focus {
	width: 200px;
	padding: 0 12px;
}


@keyframes rotate {
	0% {
		transform: rotate(0deg);
	}

	100% {
		transform: rotate(360deg);
	}
}
</style>
