// deliver-front/vue/src/layouts/components/Header/index.vue
<script lang="ts" setup>
import { ref } from 'vue'
import { ExclamationCircleOutlined, QuestionCircleOutlined, GithubOutlined } from '@ant-design/icons-vue'
const showAbout = ref(false)
const setShowAbout = (open: boolean): void => {
	showAbout.value = open
}
</script>
<template>
	<a-layout-header class="header">
		<div class="left">
			<a href="/">
				<img src="../../../../public/logo.png" style="height: 28px; width: 33px; margin-top: 16px; margin-right: 8px"
					alt="空" />
			</a>
			<a href="/">
				<h1>Deliver 企业消息推送平台</h1>
			</a>
		</div>
		<div class="right">
			<a-tooltip title="关于">
				<a style="color: #8b8b8b; font-size: 16px" @click="showAbout = true">
					<ExclamationCircleOutlined />
				</a>
			</a-tooltip>
			<a-modal v-model:open="showAbout" title="关于" centered @ok="setShowAbout(false)"
				:ok-button-props="{ disabled: true }" :cancel-button-props="{ disabled: true }" :footer="null">
				<div style="display: flex; margin-top: 20px">
					<div style="display: flex">
						<img src="../../../../public/logo.png" style="width: 66px; height: 56px" alt="null" />
						<h1 style="display: inline-block; height: 60px; line-height: 60px">Deliver</h1>
					</div>
					<div style="margin-left: 60px">
						<p>产品：Deliver 企业消息推送平台</p>
						<p>版本：v1.0.0</p>
						<a target="_blank"
							href="https://os-zero.gitee.io/deliver-website">https://os-zero.gitee.io/deliver-website</a>
					</div>
				</div>
			</a-modal>
			<a-tooltip title="疑问">
				<a target="_blank" href="https://os-zero.gitee.io/deliver-website" style="color: #8b8b8b; font-size: 16px">
					<QuestionCircleOutlined />
				</a>
			</a-tooltip>
			<a-tooltip title="Gitee">
				<a href="https://gitee.com/OS-Zero/deliver" target="_blank" style="color: #8b8b8b; font-size: 16px">
					<GithubOutlined />
				</a>
			</a-tooltip>
			<span class="avatar">
				<a-avatar style="width: 30px; height: 30px; font-size: 16px" src="mayi.png"></a-avatar>
				<span class="name">Deliver</span>
			</span>
		</div>
	</a-layout-header>
</template>
<style lang="scss" scoped>
.header {
	display: flex;
	justify-content: space-between;
	background-color: #fff;
	height: 60px;
	margin-left: -28px;
	margin-right: -28px;

	.left {
		display: flex;

		h1 {
			color: #000;
			font-size: 18px;
			height: 60px;
			line-height: 60px;
		}
	}

	.right {
		font-size: 20px;
		color: #8b8b8b;

		a {
			margin-right: 12px;
		}

		.avatar {
			display: inline-block;
			height: 100%;
			padding-right: 20px;
			padding-left: 20px;

			.name {
				margin-left: 10px;
				font-size: 15px;
			}
		}

		.avatar:hover {
			cursor: pointer;
			background-color: #f7f7f7;
		}
	}
}
</style>

// deliver-front/react/src/views/Layout/components/Header/index.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  ExclamationCircleOutlined,
  QuestionCircleOutlined,
  GithubOutlined,
  AppstoreOutlined,
  SettingOutlined
} from '@ant-design/icons';
import { Dropdown, Avatar, Modal, Menu, MenuProps, Tooltip } from 'antd';
import { logout } from '@/api/user';
import style from './index.module.scss';

const Header: React.FC = () => {
  const navigate = useNavigate();
  const [showAbout, setShowAbout] = useState(false);
  const [current, setCurrent] = useState('');

  const items = [
    {
      label: '分组管理',
      key: 'groupManage',
      icon: <AppstoreOutlined />
    },
    {
      label: '系统管理',
      key: 'systemManage',
      icon: <SettingOutlined />
    }
  ];

  const handleAction = async (key: string) => {
    switch (key) {
      case 'account':
        navigate('/systemSettings');
        break;
      case 'logout':
        await logout();
        localStorage.removeItem('access_token');
        localStorage.removeItem('user_info');
        navigate('/login');
        break;
      default:
        break;
    }
  };

  const onClick: MenuProps['onClick'] = (e) => {
    setCurrent(e.key);
    navigate(`/${e.key}`, { replace: true });
  };

  return (
    <div className={style['header']}>
      <div className={style['headerContainer']}>
        <div className={style['organization']}>
          <a href="/">
            <img className={style['organizationImg']} src="/logo.png" alt="Deliver Logo" />
          </a>
          <a href="/">
            <h1>Deliver 企业消息推送平台</h1>
          </a>
          <div className={style['header-tabs']}>
            <Menu onClick={onClick} mode="horizontal" selectedKeys={[current]} items={items} />
          </div>
        </div>
        <div className={style['headerRight']}>
          <Modal
            title="关于"
            open={showAbout}
            centered
            onCancel={() => setShowAbout(false)}
            footer={null}
          >
            <div className={style['modal-container']}>
              <div className={style['container-info']}>
                <img className={style['info_img']} src="/logo.png" alt="Logo" />
                <h1 className={style['info_title']}>Deliver</h1>
              </div>
              <div style={{ marginLeft: '60px' }}>
                <p>产品：Deliver 企业消息推送平台</p>
                <p>版本：v1.0.0</p>
                <a target="_blank" href="https://os-zero.gitee.io/deliver-website" rel="noreferrer">
                  https://os-zero.gitee.io/deliver-website
                </a>
              </div>
            </div>
          </Modal>
          <Tooltip title="关于">
            <a onClick={() => setShowAbout(true)}>
              <ExclamationCircleOutlined />
            </a>
          </Tooltip>
          <Tooltip title="疑问">
            <a target="_blank" rel="noreferrer" href="https://os-zero.gitee.io/deliver-website">
              <QuestionCircleOutlined />
            </a>
          </Tooltip>
          <Tooltip title="Gitee">
            <a href="https://gitee.com/OS-Zero/deliver" rel="noreferrer" target="_blank">
              <GithubOutlined />
            </a>
          </Tooltip>
          <Dropdown menu={{ items }} placement="bottomRight">
            <Avatar>U</Avatar>
          </Dropdown>
        </div>
      </div>
    </div>
  );
};

export default Header;
