// deliver-front/react/src/pages/Welcome.tsx
import { PageContainer } from '@ant-design/pro-components';
import { useModel } from '@umijs/max';
import { Card, theme } from 'antd';
import React from 'react';

/**
 * 每个单独的卡片，为了复用样式抽成了组件
 * @param param0
 * @returns
 */
const InfoCard: React.FC<{
  title: string;
  index: number;
  desc: string;
  href: string;
}> = ({ title, href, index, desc }) => {
  const { useToken } = theme;

  const { token } = useToken();

  return (
    <div
      style={{
        backgroundColor: token.colorBgContainer,
        boxShadow: token.boxShadow,
        borderRadius: '8px',
        fontSize: '14px',
        color: token.colorTextSecondary,
        lineHeight: '22px',
        padding: '16px 19px',
        minWidth: '220px',
        flex: 1,
      }}
    >
      <div
        style={{
          display: 'flex',
          gap: '4px',
          alignItems: 'center',
        }}
      >
        <div
          style={{
            width: 48,
            height: 48,
            lineHeight: '22px',
            backgroundSize: '100%',
            textAlign: 'center',
            padding: '8px 16px 16px 12px',
            color: '#FFF',
            fontWeight: 'bold',
            backgroundImage:
              "url('https://gw.alipayobjects.com/zos/bmw-prod/daaf8d50-8e6d-4251-905d-676a24ddfa12.svg')",
          }}
        >
          {index}
        </div>
        <div
          style={{
            fontSize: '16px',
            color: token.colorText,
            paddingBottom: 8,
          }}
        >
          {title}
        </div>
      </div>
      <div
        style={{
          fontSize: '14px',
          color: token.colorTextSecondary,
          textAlign: 'justify',
          lineHeight: '22px',
          marginBottom: 8,
        }}
      >
        {desc}
      </div>
      <a href={href} target="_blank" rel="noreferrer">
        了解更多 {'>'}
      </a>
    </div>
  );
};

const Welcome: React.FC = () => {
  const { token } = theme.useToken();
  const { initialState } = useModel('@@initialState');
  return (
    <PageContainer>
      <Card
        style={{
          borderRadius: 8,
        }}
        bodyStyle={{
          backgroundImage:
            initialState?.settings?.navTheme === 'realDark'
              ? 'background-image: linear-gradient(75deg, #1A1B1F 0%, #191C1F 100%)'
              : 'background-image: linear-gradient(75deg, #FBFDFF 0%, #F5F7FF 100%)',
        }}
      >
        <div
          style={{
            backgroundPosition: '100% -30%',
            backgroundRepeat: 'no-repeat',
            backgroundSize: '274px auto',
            backgroundImage:
              "url('https://gw.alipayobjects.com/mdn/rms_a9745b/afts/img/A*BuFmQqsB2iAAAAAAAAAAAAAAARQnAQ')",
          }}
        >
          <div
            style={{
              fontSize: '20px',
              color: token.colorTextHeading,
            }}
          >
            欢迎使用 Deliver 消息推送平台
          </div>
          <p
            style={{
              fontSize: '14px',
              color: token.colorTextSecondary,
              lineHeight: '22px',
              marginTop: 16,
              marginBottom: 32,
              width: '65%',
            }}
          >
            Deliver 是一个面向企业的全面消息推送平台，旨在提供企业内部沟通和协作的便捷解决方案。它以轻量级部署、简单易用、支持多种通信渠道为特点，为企业提供高效的消息传递和通知功能。
          </p>
          <div
            style={{
              display: 'flex',
              flexWrap: 'wrap',
              gap: 16,
            }}
          >
            <InfoCard
              index={1}
              href="https://os-zero.gitee.io/website/"
              title="社区官网"
              desc="欢迎访问 OSZero 官方网站，Open Source Zero（零号开源）由一群充满技术热情的开发者创建。加入我们，一同探索开源世界！"
            />
            <InfoCard
              index={2}
              title="快速开始"
              href="https://os-zero.gitee.io/website/project/deliver/start.html"
              desc="立即启动 Deliver 企业消息推送平台，发送属于您的首条消息~"
            />
            <InfoCard
              index={3}
              title="开发者文档"
              href="https://os-zero.gitee.io/website/project/deliver/developer.html"
              desc="探索开发者专属的设计和二次开发文档，创建您独一无二的企业消息推送平台！"
            />
            <InfoCard
              index={4}
              title="用户指南"
              href="https://os-zero.gitee.io/website/project/deliver/guide.html"
              desc="在这里，您将学会如何创建消息模板、配置必要信息以及发送各种类型的消息。现在就开始吧~"
            />
            <InfoCard
              index={5}
              title="运维部署"
              href="https://os-zero.gitee.io/website/project/deliver/deploy.html"
              desc="支持多种部署方式（本地、Docker、Linux Shell），简单快捷的部署方式，让我们开始搭建吧！"
            />
            <InfoCard
              index={6}
              title="交流讨论"
              href="https://os-zero.gitee.io/website/community/communicate.html"
              desc="欢迎加入我们的社区官方交流讨论群，快速获得答疑解惑，赶紧一起加入吧~"
            />
          </div>
        </div>
      </Card>
    </PageContainer>
  );
};

export default Welcome;

// deliver-front/vue/src/views/Welcome/index.vue
<script lang="ts" setup>
import { ref } from 'vue'
interface Card {
	title: string
	desc: string
	link: string
}
const cards = ref<Card[]>([
	{
		title: '社区官网',
		desc: '欢迎访问 OSZero 官方网站，Open Source Zero（零号开源）由一群充满技术热情的开发者创建。加入我们，一同探索开源世界！',
		link: 'https://os-zero.gitee.io/website/'
	},
	{
		title: '快速开始',
		desc: '立即启动 Deliver 企业消息推送平台，发送属于您的首条消息~',
		link: 'https://os-zero.gitee.io/website/project/deliver/start.html'
	},
	{
		title: '开发者文档',
		desc: '探索开发者专属的设计和二次开发文档，创建您独一无二的企业消息推送平台！',
		link: 'https://os-zero.gitee.io/website/project/deliver/developer.html'
	},
	{
		title: '用户指南',
		desc: '在这里，您将学会如何创建消息模板、配置必要信息以及发送各种类型的消息。现在就开始吧~',
		link: 'https://os-zero.gitee.io/website/project/deliver/guide.html'
	},
	{
		title: '运维部署',
		desc: '支持多种部署方式（本地、Docker、Linux Shell），简单快捷的部署方式，让我们开始搭建吧！',
		link: 'https://os-zero.gitee.io/website/project/deliver/deploy.html'
	},
	{
		title: '交流讨论',
		desc: '欢迎加入我们的社区官方交流讨论群，快速获得答疑解惑，赶紧一起加入吧~',
		link: 'https://os-zero.gitee.io/website/community/communicate.html'
	}
])
</script>
<template>
	<div id="welcome-container">
		<h1>欢迎使用 Deliver 企业消息推送平台</h1>
		<p>
			Deliver
			是一个面向企业的全面消息推送平台，旨在提供企业内部沟通和协作的便捷解决方案。它以轻量级部署、简单易用、支持多种通信渠道为特点，为企业提供高效的消息传递和通知功能。
		</p>
		<a-row :gutter="[16, 16]">
			<a-col class="gutter-row" :span="8" v-for="item in cards" :key="item.title">
				<a-card style="height: 100%">
					<a-card-meta :title="item.title" :description="item.desc" style="height: 100px">
						<template #avatar>
							<a-avatar
								:size="40"
								class="avatar"
								src="https://gw.alipayobjects.com/zos/bmw-prod/daaf8d50-8e6d-4251-905d-676a24ddfa12.svg" />
						</template>
					</a-card-meta>
					<template #actions>
						<a style="color: #1677ff" :href="item.link" target="_blank">了解更多 ></a>
					</template>
				</a-card>
			</a-col>
		</a-row>
	</div>
</template>
<style lang="scss" scoped>
#welcome-container {
	padding: 24px;
	background-image: linear-gradient(to bottom, #eff3ff, #f0f5ff);
	border-radius: 6px;

	h1 {
		font-size: 20px;
	}

	& > p {
		width: 65%;
		margin-top: 16px;
		margin-bottom: 32px;
		font-size: 14px;
		line-height: 22px;
		color: rgb(0 0 0 / 65%);
	}

	a:hover {
		color: #6ea2d7 !important;
	}
}
</style>
