// deliver-front/vue/src/views/SystemManage/pages/Sentinel/index.vue
<script lang="ts" setup>
import { ref } from 'vue';

const iframeSrc = ref('https://oszero.cn/');
</script>

<template>
  <div class="iframe-container">
    <a-input class="iframe-input" placeholder="请输入网址" v-model:value="iframeSrc"></a-input>
    <iframe :src="iframeSrc" frameborder="0" width="100%" height="100%"></iframe>
  </div>
</template>

<style lang="scss" scoped>
.iframe-container {
  position: relative;
}

.iframe-input {
  width: 300px;
  position: absolute;
  right: 0;
  top: -36px;
}
</style>

// deliver-front/react/src/views/SystemManage/pages/Sentinel/index.tsx
import { useState } from 'react';
import { Input } from 'antd';
import styles from './index.module.scss';

const Sentinel = () => {
  const [iframeSrc, setIframeSrc] = useState('https://oszero.cn/');

  return (
    <div className={styles['iframeContainer']}>
      <Input
        className={styles['iframeInput']}
        placeholder="请输入网址"
        value={iframeSrc}
        onChange={(e) => setIframeSrc(e.target.value)}
      />
      <iframe
        src={iframeSrc}
        frameBorder="0"
        width="100%"
        height="100%"
        sandbox="allow-same-origin allow-scripts allow-popups allow-forms"
        referrerPolicy="no-referrer"
      />
    </div>
  );
};

export default Sentinel;
