// deliver-front/react/src/views/Layout/components/SideBar/index.tsx
import React, { useState } from 'react';
import { Layout, Menu, Button } from 'antd';
import { MenuUnfoldOutlined, MenuFoldOutlined } from '@ant-design/icons';
import { useNavigate } from 'react-router-dom';
import type { MenuProps } from 'antd';
import styles from './index.module.scss';
import { usePathMatch } from '../../../../hooks/usePathMatch';

interface SideBarProps {
  items: MenuProps['items'];
}

const SideBar: React.FC<SideBarProps> = ({ items }) => {
  const [collapsed, setCollapsed] = useState(false);
  const navigate = useNavigate();
  const { selectedKeys } = usePathMatch();

  const toggleCollapsed = () => {
    setCollapsed(!collapsed);
  };

  const handleMenuClick: MenuProps['onClick'] = (info) => {
    navigate(info.key);
  };

  return (
    <Layout.Sider collapsed={collapsed} theme="light" className={styles['siderContainer']}>
      <Menu mode="inline" items={items} selectedKeys={selectedKeys} onClick={handleMenuClick} />
      <footer className={styles['siderFooter']}>
        <Button type="text" className={styles['footerButton']} onClick={toggleCollapsed}>
          {collapsed ? <MenuUnfoldOutlined /> : <MenuFoldOutlined />}
        </Button>
      </footer>
    </Layout.Sider>
  );
};

export default SideBar;

// deliver-front/vue/src/views/Layout/components/SideBar/index.vue
<script lang="ts" setup>
import { reactive } from 'vue'
import {
	MenuUnfoldOutlined,
	MenuFoldOutlined
} from '@ant-design/icons-vue'
import { ItemType } from 'ant-design-vue'
defineProps<{
	items: ItemType[]
}>()
const state = reactive({
	collapsed: false
});
const toggleCollapsed = () => {
	state.collapsed = !state.collapsed;
};
</script>

<template>
	<a-layout-sider :collapsed="state.collapsed" theme="light">
		<a-menu :items="items" mode="inline" />
		<footer class="sider-footer">
			<a-button type="text" class="footer_button" @click="toggleCollapsed">
				<MenuUnfoldOutlined v-if="state.collapsed" />
				<MenuFoldOutlined v-else />
			</a-button>
		</footer>
	</a-layout-sider>
</template>

<style lang="scss" scoped>
.ant-layout-sider {
	position: relative;

	.sider-footer {
		position: absolute;
		display: flex;
		height: 40px;
		bottom: 0;
		width: 100%;
		border-top: 1px solid var(--gray-lightest);

		.footer_button {
			width: 100%;
			margin: auto;

			&:hover {
				background-color: transparent
			}
		}
	}
}
</style>
