// deliver-front/vue/src/views/Layout/index.vue
<script lang="ts" setup>
import Header from './components/Header/index.vue'
import Banner from './components/Banner/index.vue'
import Breadcrumb from './components/Breadcrumb/index.vue'
import SideBar from './components/SideBar/index.vue'
import {
	GithubOutlined
} from '@ant-design/icons-vue'
</script>

<template>
	<a-layout>
		<div class="layout_header">
			<Banner class="header_banner" />
			<Header></Header>
		</div>
		<a-layout>
			<SideBar></SideBar>
			<a-layout class="layout-section">
				<Breadcrumb class="section_breadcrumb" />
				<a-layout-content>
					<RouterView></RouterView>
				</a-layout-content>
				<a-layout-footer>
					<div class="footer_organization">
						Deliver 企业消息推送平台
						<a class="organization_link" href="https://gitee.com/OS-Zero" target="_blank">
							<GithubOutlined />
						</a>
						OSZero 开源社区出品
					</div>
					<div>Copyright © 2023 OSZero. All rights reserved.</div>
				</a-layout-footer>
			</a-layout>
		</a-layout>
	</a-layout>
</template>
<style scoped lang="scss">
.ant-layout {
	height: 100%;

	.layout-section {
		padding: var(--spacing-md);

		.section_breadcrumb {
			margin-bottom: var(--spacing-md)
		}

		.ant-layout-footer {
			text-align: center;
			background-color: var(--gray-lightest);
			color: var(--gray-dark);
		}

		.footer_organization {
			margin-bottom: var(--spacing-sm)
		}

		.organization_link {
			color: var(--gray-dark);
			font-size: var(--spacing-md);
		}
	}
}
</style>

// deliver-front/react/src/views/Layout/index.tsx
import React, { useState, useEffect } from 'react';
import { Layout } from 'antd';
import { useLocation, Outlet } from 'react-router-dom';
import { GithubOutlined } from '@ant-design/icons';
import Banner from './components/Banner';
import Header from './components/Header';
import SideBar from './components/SideBar';
import Breadcrumb from './components/Breadcrumb';
import styles from './index.module.scss';
import { menuConfig } from './constant';

const { Content, Footer } = Layout;

const AppLayout: React.FC = () => {
  const location = useLocation();
  const [menuItems, setMenuItems] = useState<
    { key: string; label: string | React.ReactElement; icon?: React.ReactElement }[]
  >([]);

  useEffect(() => {
    const path = location.pathname;
    let menuItems: any[] = [];

    switch (true) {
      case path.includes('groupManage') && !path.endsWith('groupManage'):
        menuItems = menuConfig?.groupManage;
        break;
      case path.includes('systemManage') && !path.endsWith('systemManage'):
        menuItems = menuConfig?.systemManage;
        break;
      default:
        menuItems = [];
    }

    setMenuItems(menuItems);
  }, [location.pathname]);

  return (
    <Layout style={{ height: '100vh' }}>
      <Banner />
      <Layout>
        <Header />
        <Layout>
          {menuItems.length > 0 && <SideBar items={menuItems} />}
          <Layout className={styles['layout-section']}>
            <div className={styles['section_breadcrumb']}>
              <Breadcrumb />
            </div>
            <Content>
              <Outlet />
            </Content>
            <Footer style={{ textAlign: 'center', background: 'var(--gray-lightest)' }}>
              <div className={styles['footer_organization']}>
                Deliver 企业消息推送平台{' '}
                <a
                  className={styles['organization_link']}
                  href="https://gitee.com/OS-Zero"
                  target="_blank"
                  rel="noreferrer"
                >
                  <GithubOutlined />
                </a>{' '}
                OSZero 开源社区出品
              </div>
              <div>Copyright 2023 OSZero. All rights reserved.</div>
            </Footer>
          </Layout>
        </Layout>
      </Layout>
    </Layout>
  );
};

export default AppLayout;
