// deliver-front/vue/src/views/Layout/components/Breadcrumb/index.vue
<script lang="ts" setup>
import { ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
interface Route {
	path: string
	breadcrumbName: string
	children?: Array<{
		path: string
		breadcrumbName: string
	}>
}
const routes = ref<Route[]>([])
const route = useRoute()
const router = useRouter()
watch(
	route,
	() => {
		routes.value = []
		route.matched.forEach((item) => {
			routes.value.push({ path: item.path, breadcrumbName: item.name as string })
		})
	},
	{
		immediate: true,
	},
)
const handleClick = (path: string) => {
	if (path === '/groupManage') localStorage.removeItem('group_id')
	router.push(path)
}

</script>
<template>
	<a-breadcrumb :routes="routes" separator="/">
		<template #itemRender="{ route }">
			<span v-if="routes.indexOf(route) === routes.length - 1">
				{{ route.breadcrumbName }}
			</span>
			<a @click="handleClick(route.path)" v-else>
				{{ route.breadcrumbName }}
			</a>
		</template>
	</a-breadcrumb>
</template>
<style lang="sass" scoped></style>

// deliver-front/react/src/views/Layout/components/Breadcrumb/index.tsx
import React from 'react';
import { Breadcrumb as AntBreadcrumb } from 'antd';
import { useLocation, matchRoutes, useNavigate } from 'react-router-dom';
import routes from '@/router';

interface BreadcrumbRoute {
  path: string;
  breadcrumbName: string;
}

const Breadcrumb: React.FC = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const matchedRoutes = matchRoutes(routes, location);

  const generateBreadcrumbs = (matchedRoutes: any) => {
    const breadcrumbs: BreadcrumbRoute[] = [];
    matchedRoutes?.forEach((match: any) => {
      const route = match.route;
      if (route.path) {
        breadcrumbs.push({
          path: match.pathname,
          breadcrumbName: route.name || 'Unknown'
        });
      }
    });
    return breadcrumbs;
  };

  const handleBreadcrumbClick = (route: BreadcrumbRoute) => {
    if (route.path.includes('/groupManage')) {
      // 清除 group 相关信息
      localStorage.removeItem('group_id');
    }

    navigate(route.path, { replace: true });
  };

  const breadcrumbRoutes = generateBreadcrumbs(matchedRoutes);

  const items = breadcrumbRoutes.map((route, index) => {
    const last = index === breadcrumbRoutes.length - 1;
    return {
      key: route.path,
      title: last ? (
        <span>{route.breadcrumbName}</span>
      ) : (
        <div
          onClick={() => handleBreadcrumbClick(route)}
          style={{ cursor: 'pointer', display: 'inline' }}
        >
          {route.breadcrumbName}
        </div>
      )
    };
  });

  return <AntBreadcrumb separator="/" items={items} />;
};

export default Breadcrumb;
