// deliver-front/react/src/views/Login/components/ForgotForm/index.tsx
import { useState, useRef, useEffect } from 'react';
import { Form, Input, Button, message, Tooltip } from 'antd';
import { forgotPwd } from '@/api/user';
import { useVerify } from '@/hooks/useVerify';
import styles from './index.module.scss';
import {
  emailValidationRule,
  passwordValidationRule,
  verificationCodeValidationRule
} from '@/views/Login/constant';
import { omitProperty } from '@/utils/omitProperty';

interface ForgotInfo {
  userEmail: string;
  userPassword: string;
  confirmPwd: string;
  verificationCode: string;
}

const ForgotForm: React.FC<{ onOk: () => void }> = ({ onOk }) => {
  const [forgotData, setForgotData] = useState<ForgotInfo>({
    userEmail: '',
    userPassword: '',
    confirmPwd: '',
    verificationCode: ''
  });

  const formRef = useRef<any>(null);
  const { verifyDisabled, verifyContent, handleVerify, checkEmailFormat } = useVerify({
    email: forgotData.userEmail
  });

  const validatePwd = (_: any, value: string) => {
    if (value !== forgotData.userPassword) {
      return Promise.reject('两次输入密码不相同');
    }
    return Promise.resolve();
  };

  const handleBtnTips = () => {
    return verifyContent.includes('验证码') ? '请先填写正确的邮箱地址' : '';
  };

  const handleForgot = async () => {
    try {
      await formRef.current.validateFields();
      await forgotPwd(omitProperty(forgotData, 'confirmPwd'));
      message.success('修改密码成功');
      onOk();
    } catch (error) {
      console.log('error', error);
    }
  };

  useEffect(() => {
    const validateEmailFormat = async () => {
      if (forgotData.userEmail) {
        await checkEmailFormat();
      }
    };

    validateEmailFormat();
  }, [forgotData.userEmail, checkEmailFormat]);

  return (
    <Form ref={formRef} layout="vertical">
      <Form.Item name="userEmail" rules={[emailValidationRule]} validateTrigger={['onBlur']}>
        <Input
          value={forgotData.userEmail}
          onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
            setForgotData({ ...forgotData, userEmail: e.target.value })
          }
          placeholder="请输入邮箱"
        />
      </Form.Item>
      <Form.Item name="userPassword" rules={[passwordValidationRule]} validateTrigger={['onBlur']}>
        <Input.Password
          maxLength={16}
          value={forgotData.userPassword}
          onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
            setForgotData({ ...forgotData, userPassword: e.target.value })
            if (forgotData?.confirmPwd) {
              formRef.current.validateFields(['confirmPwd']);
            }
          }}
          placeholder="请输入密码"
        />
      </Form.Item>
      <Form.Item
        name="confirmPwd"
        rules={[{ validator: validatePwd }]}
        validateTrigger={['onBlur']}
      >
        <Input.Password
          maxLength={16}
          value={forgotData.confirmPwd}
          onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
            setForgotData({ ...forgotData, confirmPwd: e.target.value })
          }
          placeholder="请确认密码"
        />
      </Form.Item>
      <Form.Item
        name="verificationCode"
        rules={[verificationCodeValidationRule]}
        validateTrigger={['onBlur']}
      >
        <div className={styles.verify}>
          <Input
            maxLength={6}
            value={forgotData.verificationCode}
            onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
              setForgotData({ ...forgotData, verificationCode: e.target.value })
            }
            placeholder="请输入6位验证码"
          />
          <Tooltip title={verifyDisabled ? handleBtnTips() : ''}>
            <Button
              className={styles.verifyBtn}
              disabled={verifyDisabled}
              onClick={() => handleVerify()}
            >
              {verifyContent}
            </Button>
          </Tooltip>
        </div>
      </Form.Item>
      <Form.Item>
        <Button className={styles.submitBtn} type="primary" onClick={handleForgot}>
          确认
        </Button>
      </Form.Item>
    </Form>
  );
};

export default ForgotForm;

// deliver-front/vue/src/views/Login/components/ForgotForm.vue
<script lang="ts" setup>
import { ref, reactive, watch } from 'vue';
import { ForgotInfo } from '../type';
import type { Rule } from 'ant-design-vue/es/form';
import { validateEmail } from '@/utils/validate';
import { forgotPwd } from '@/api/user';
import { omitProperty } from '@/utils/utils';
import { message } from 'ant-design-vue';
import { useVerify } from '@/utils/hooks';
import { getRules } from '@/config/rules';

const emits = defineEmits<{
	onOk: []
}>()
const forgotData = reactive<ForgotInfo>({
	userEmail: '',
	userPassword: '',
	confirmPwd: '',
	verificationCode: ''
})
const validatePwd = () => {
	if (forgotData.confirmPwd === '') return Promise.reject("请确认密码")
	return forgotData.confirmPwd === forgotData.userPassword ? Promise.resolve() : Promise.reject("两次输入密码不相同")
}
const rules: Record<string, Rule[]> = {
	confirmPwd: [{ validator: validatePwd, trigger: 'blur' }],
	...getRules(['userEmail', 'userPassword', 'verificationCode'])
};

const formRef = ref()

const handleForgot = () => {
	formRef.value
		.validate()
		.then(async () => {
			await forgotPwd(omitProperty(forgotData, "confirmPwd"))
			message.success("修改密码成功")
			emits("onOk")
		})
		.catch(error => {
			console.log('error', error);
		});
}
const { state, handleVarify, onFinished } = useVerify()
const _validateEmail = async () => {
	try {
		await validateEmail(null, forgotData.userEmail)
		!state.loading && (state.verifyDisabled = false)
	} catch (error) {
		state.verifyDisabled = true
	}
}
onFinished(() => {
	_validateEmail()
})
watch(forgotData, _validateEmail, {
	immediate: true
})
</script>

<template>
	<a-form ref="formRef" :model="forgotData" :rules="rules">
		<a-form-item name="userEmail">
			<a-input v-model:value.trim="forgotData.userEmail" placeholder="请输入邮箱" />
		</a-form-item>
		<a-form-item name="userPassword">
			<a-input-password v-model:value.trim="forgotData.userPassword" placeholder="请输入密码" />
		</a-form-item>
		<a-form-item name="confirmPwd">
			<a-input-password v-model:value.trim="forgotData.confirmPwd" placeholder="请确认密码" />
		</a-form-item>
		<a-form-item name="verificationCode">
			<div class="verify">
				<a-input v-model:value.trim="forgotData.verificationCode" placeholder="请输入验证码" />
				<a-button class="verify_btn" :disabled="state.verifyDisabled" @click="handleVarify(forgotData.userEmail)">{{
					state.verifyContent
				}}</a-button>
			</div>
		</a-form-item>
		<a-form-item>
			<a-button class="submit_btn" type="primary" html-type="submit" @click="handleForgot">确认</a-button>
		</a-form-item>
	</a-form>
</template>

<style lang="scss" scoped>
.verify {
	display: flex;

	.verify_btn {
		margin-left: var(--spacing-sm)
	}
}

.submit_btn {
	width: 100%
}
</style>
