// deliver-front/react/src/views/Login/components/LoginForm/index.tsx
import { useState, useRef } from 'react';
import { Form, Input, Button, message } from 'antd';
import { login, getCurrentLoginUserInfo } from '@/api/user';
import { useNavigate } from 'react-router-dom';
import { emailValidationRule, passwordValidationRule } from '@/views/Login/constant';

interface UserInfo {
  userEmail: string;
  userPassWord: string;
}

const LoginForm: React.FC = () => {
  const [loginData, setLoginData] = useState<UserInfo>({
    userEmail: '',
    userPassWord: ''
  });

  const formRef = useRef<any>(null);
  const navigate = useNavigate();

  const handleLogin = async () => {
    try {
      await formRef?.current?.validateFields();
      const res = await login(loginData);
      if (res?.token) {
        localStorage.setItem('access_token', res.token);
        message.success('登录成功');
        navigate('/');
        const _res = await getCurrentLoginUserInfo();
        localStorage.setItem('userInfo', JSON.stringify(_res));
      }
    } catch (error) {
      console.log('error', error);
    }
  };

  return (
    <Form ref={formRef} layout="vertical">
      <Form.Item name="userEmail" rules={[emailValidationRule]} validateTrigger={['onBlur']}>
        <Input
          value={loginData.userEmail}
          onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
            setLoginData({ ...loginData, userEmail: e.target.value })
          }
          placeholder="请输入邮箱"
        />
      </Form.Item>
      <Form.Item name="userPassWord" rules={[passwordValidationRule]} validateTrigger={['onBlur']}>
        <Input.Password
          value={loginData.userPassWord}
          onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
            setLoginData({ ...loginData, userPassWord: e.target.value })
          }
          placeholder="请输入密码"
        />
      </Form.Item>
      <Form.Item>
        <Button style={{ width: '100%' }} type="primary" onClick={handleLogin}>
          登录
        </Button>
      </Form.Item>
    </Form>
  );
};

export default LoginForm;

// deliver-front/vue/src/views/Login/components/LoginForm.vue
<script lang="ts" setup>
import { ref, reactive } from 'vue';
import { UserInfo } from '../type';
import type { Rule } from 'ant-design-vue/es/form';
import { login, getCurrentLoginUserInfo } from "@/api/user";
import { useRouter } from 'vue-router';
import { message } from 'ant-design-vue'
import { getRules } from '@/config/rules';
const router = useRouter()
const loginData = reactive<UserInfo>({
	userEmail: '',
	userPassword: ''
})
const rules: Record<string, Rule[]> = getRules(['userEmail', 'userPassword'])
const formRef = ref()
const handleLogin = function () {
	formRef.value
		.validate()
		.then(async () => {
			const res = await login(loginData)
			localStorage.setItem('access_token', res.token)
			message.success('登录成功')
			router.push('/')
			const _res = await getCurrentLoginUserInfo()
			localStorage.setItem('user_info', JSON.stringify(_res))
		})
		.catch(error => {
			console.log('error', error);
		});
}
</script>

<template>
	<a-form ref="formRef" :model="loginData" :rules="rules">
		<a-form-item name="userEmail">
			<a-input v-model:value.trim="loginData.userEmail" placeholder="请输入邮箱" />
		</a-form-item>
		<a-form-item name="userPassword">
			<a-input-password v-model:value.trim="loginData.userPassword" placeholder="请输入密码" />
		</a-form-item>
		<a-form-item>
			<a-button class="submit_btn" type="primary" html-type="submit" @click="handleLogin">登录</a-button>
		</a-form-item>
	</a-form>
</template>

<style lang="scss" scoped>
.submit_btn {
	width: 100%
}
</style>
