// deliver-front/react/src/views/Layout/components/Breadcrumb/index.tsx
import React from 'react';
import { Breadcrumb as AntBreadcrumb } from 'antd';
import { Link, useLocation, matchRoutes } from 'react-router-dom';
import routes from '@/router';

interface BreadcrumbRoute {
  path: string;
  breadcrumbName: string;
}
const Breadcrumb: React.FC = () => {
  const location = useLocation();
  const matchedRoutes = matchRoutes(routes, location);

  const generateBreadcrumbs = (matchedRoutes: any) => {
    const breadcrumbs: BreadcrumbRoute[] = [];
    matchedRoutes?.forEach((match: any) => {
      const route = match.route;
      if (route.path) {
        breadcrumbs.push({
          path: match.pathname,
          breadcrumbName: route.name || 'Unknown'
        });
      }
    });
    return breadcrumbs;
  };

  const breadcrumbRoutes = generateBreadcrumbs(matchedRoutes);

  const items = breadcrumbRoutes.map((route, index) => {
    const last = index === breadcrumbRoutes.length - 1;
    return {
      key: route.path,
      title: last ? (
        <span>{route.breadcrumbName}</span>
      ) : (
        <Link to={route.path}>{route.breadcrumbName}</Link>
      )
    };
  });

  return <AntBreadcrumb separator="/" items={items} />;
};

export default Breadcrumb;

// deliver-front/vue/src/layouts/components/Breadcrumb/index.vue
<script lang="ts" setup>
import { ref, watch } from 'vue'
import { useRoute } from 'vue-router'
interface Route {
	path: string
	breadcrumbName: string
	children?: Array<{
		path: string
		breadcrumbName: string
	}>
}
const routes = ref<Route[]>([])
const route = useRoute()
watch(
	route,
	() => {
		routes.value = []
		route.matched.forEach((item) => {
			routes.value.push({ path: item.path, breadcrumbName: item.name as string })
		})
	},
	{
		immediate: true,
	},
)
</script>
<template>
	<a-breadcrumb :routes="routes" separator="/">
		<template #itemRender="{ route, paths }">
			<span v-if="routes.indexOf(route) === routes.length - 1">
				{{ route.breadcrumbName }}
			</span>
			<router-link v-else :to="`${paths.join('/')}`">
				{{ route.breadcrumbName }}
			</router-link>
		</template>
	</a-breadcrumb>
</template>
<style lang="sass" scoped></style>
